name: golangci-lint
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  test:
    name: build/test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: go build

      - name: tests
        run: make test

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [ lint, test ]
    steps:
      - uses: actions/checkout@v3

      - name: setup aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_ACCESS_KEY }}
          aws-region: us-west-2

      - name: package build for lambda
        run: make lambda

      - name: upload to aws s3
        run: aws s3 cp lambda.zip s3://tach-bucket/lambda.zip

      - name: update aws lambda
        run: aws lambda update-function-code --function-name getPizzaDeals --s3-bucket $tach-bucket --s3-key lambda.zip